name: Comprehensive Tests

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - main
      - "release/**"
  workflow_dispatch:

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  swift-cookie-creator:
    name: Build Swift CookieCreator
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Build CookieCreator
        run: |
          cd scripts/CookieCreator
          swift build

      - name: Upload CookieCreator binary
        uses: actions/upload-artifact@v4
        with:
          name: cookie-creator-binary
          path: scripts/CookieCreator/.build/
          retention-days: 7

  test-fixtures:
    name: Create Test Fixtures
    runs-on: macos-latest
    needs: swift-cookie-creator
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download CookieCreator binary
        uses: actions/download-artifact@v4
        with:
          name: cookie-creator-binary
          path: scripts/CookieCreator/.build/

      - name: Make binary executable
        run: |
          find scripts/CookieCreator/.build -name "CookieCreator" -type f -exec chmod +x {} \;

      - name: Create Binary Cookie Test Fixtures
        run: |
          cd scripts
          chmod +x create-binary-cookies.sh
          ./create-binary-cookies.sh

      - name: Upload test fixtures
        uses: actions/upload-artifact@v4
        with:
          name: test-fixtures
          path: scripts/Cookies.binarycookies
          retention-days: 30

  advanced-tests:
    name: Run Advanced Test Scripts
    runs-on: macos-latest
    needs: [test-fixtures]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download test fixtures
        uses: actions/download-artifact@v4
        with:
          name: test-fixtures
          path: scripts/

      - name: Run binary cookies test
        run: pnpm exec tsx scripts/test-binarycookies.ts

      - name: Run decoder test
        run: pnpm exec tsx scripts/test-decoder.ts

      - name: Run Safari cookies test
        run: pnpm exec tsx scripts/test-safari-cookies.ts

      - name: Validate cookie structure
        run: pnpm exec tsx scripts/validate-cookie-structure.ts

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: advanced-test-results
          path: |
            scripts/test-results/
            scripts/logs/
          retention-days: 7
