name: Cross-Platform Cookie Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build
        run: pnpm run build
      
      - name: Run tests
        run: pnpm test
      
      - name: Test Chrome cookie retrieval (Windows)
        run: |
          # Create a test Chrome cookie database
          $chromeDir = "$env:LOCALAPPDATA\Google\Chrome\User Data\Default"
          New-Item -ItemType Directory -Force -Path $chromeDir
          
          # Test the CLI
          node dist/cli.cjs --help
        shell: pwsh
      
      - name: Install optional DPAPI package
        run: pnpm add @primno/dpapi
        continue-on-error: true
      
      - name: Integration test - Chrome on Windows
        run: |
          # Test the CLI with Chrome browser option
          Write-Host "Testing Chrome cookie retrieval via CLI..."
          
          # Test --help to ensure CLI is working
          node dist/cli.cjs --help
          
          # Test Chrome cookie query (will fail gracefully without real Chrome data)
          node dist/cli.cjs --browser chrome "*" .example.com
          if ($LASTEXITCODE -ne 0) { Write-Host "Expected error: No Chrome profile found" }
          
          Write-Host "Chrome CLI integration test completed"
        shell: pwsh

  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build
        run: pnpm run build
      
      - name: Run tests
        run: pnpm test
      
      - name: Install Linux keyring tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-1-0 libsecret-tools python3-keyring
      
      - name: Test Chrome cookie retrieval (Linux)
        run: |
          # Create test Chrome directory structure
          mkdir -p ~/.config/google-chrome/Default
          
          # Test the CLI
          node dist/cli.cjs --help
      
      - name: Integration test - Chrome on Linux
        run: |
          # Test the CLI with Chrome browser option
          echo "Testing Chrome cookie retrieval via CLI..."
          
          # Test --help to ensure CLI is working
          node dist/cli.cjs --help
          
          # Test Chrome cookie query (will fail gracefully without real Chrome data)
          node dist/cli.cjs --browser chrome '*' .example.com || echo "Expected error: No Chrome profile found"
          
          echo "Chrome CLI integration test completed"
      
      - name: Test multiple browsers
        run: |
          echo "Testing multiple browsers via CLI..."
          
          # Test different browser options
          for browser in chrome brave edge opera vivaldi; do
            echo "Testing $browser..."
            node dist/cli.cjs --browser $browser --help || echo "$browser: Expected error"
          done
          
          echo "Multi-browser CLI test completed"

  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build
        run: pnpm run build
      
      - name: Run tests
        run: pnpm test
      
      - name: Test Chrome cookie retrieval (macOS)
        run: |
          # Test the CLI
          node dist/cli.cjs --help
          
          # Create test directory structure
          mkdir -p ~/Library/Application\ Support/Google/Chrome/Default
      
      - name: Integration test - Chrome on macOS
        run: |
          # Test the CLI with Chrome browser option
          echo "Testing Chrome cookie retrieval via CLI..."
          
          # Test --help to ensure CLI is working
          node dist/cli.cjs --help
          
          # Test Chrome cookie query (will fail gracefully without real Chrome data)
          node dist/cli.cjs --browser chrome '*' .example.com || echo "Expected error: No Chrome profile found"
          
          echo "Chrome CLI integration test completed"